apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-level-resources
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - helm:
      releaseName: cluster-level-resources
      valueFiles:
      - $values/ardac1dmo/cluster-level-resources/cluster-values.yaml
    path: helm/cluster-level-resources
    repoURL: https://github.com/Su-informatics-lab/gen3-helm
  - ref: values
    repoURL: 'https://github.com/Su-informatics-lab/gen3-gitops.git'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
