apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ardac2prd-portal-aliases
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/group.name: ardac2prd
    alb.ingress.kubernetes.io/group.order: "10"
spec:
  ingressClassName: alb
  rules:
    - host: portal.ardac.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: revproxy-service
                port:
                  number: 80
    - host: archive.portal.ardac.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: revproxy-service
                port:
                  number: 80
