apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-ardac1dmo
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: master
      helm:
        releaseName: gen3
        valueFiles:
          - $values/ardac1dmo/portal.ardac.org/values.yaml
    - repoURL: 'https://github.com/Su-informatics-lab/gen3-gitops.git'
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      selfHeal: true