cluster: "ardac-prod-one"

accountNumber: "742378880825"

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: true
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

cert-manager:
  enabled: true

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

external-secrets:
  enabled: true

fluentd:
  enabled: true
  configuration:
    enabled: false

kube-state-metrics:
  enabled: true
  configuration:
    enabled: false

grafana-alloy:
  enabled: false
  configuration:
    enabled: false

karpenter:
  enabled: true
  awsRegion" : "us-east-2"
  targetRevision: "1.0.8"

karpenter-crds:
  amiSelectorName: "amazon-eks-node-al2023-x86_64-standard-1.31-*"
  selectorTag: ardac-prod-one
  migration: true
  default:
    consolidationPolicy: "WhenEmptyOrUnderutilized"
    consolidateAfter: "10m"
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
          - spot
      - key: kubernetes.io/arch
        operator: In
        values:
          - amd64
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
          - r
          - c
          - m
          - t
  jupyter:
    consolidationPolicy: "WhenEmptyOrUnderutilized"
    consolidateAfter: "10m"
  workflow:
    consolidationPolicy: "WhenEmptyOrUnderutilized"
    consolidateAfter: "10m"

vpc-cni:
  enabled: true
  configuration:
    enabled: false